import type { Metadata } from 'next';

import '@/app/globals.css';
import { Drawers } from '@/components/drawers/Drawers';
import { Header } from '@/components/layout/Header';
import { DrawerContextProvider } from '@/contexts/DrawerContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <body>
        <DrawerContextProvider>
          <Header />
          {children}
          <Drawers />
        </DrawerContextProvider>
      </body>
    </html>
  );
}
